version: '3.8'
services:
    pms-docker:
        container_name: plex
        network_mode: host
        hostname: plex
        env_file:
          - plex.env
        # runtime: nvidia
        environment:
            - TZ=America/Sao_Paulo
            - PLEX_UID=1000
            - PLEX_GID=1000
            - ADVERTISE_IP= #ip:port here e.g. http://127.0.0.1:32400
            # - NVIDIA_VISIBLE_DEVICES=GPU-04aeacae-0ae1-25b6-1504-a4bec4ed2da9 #change as needed
            # - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
        volumes:
            - /var/docker/plex/config:/config
            - /var/docker/plex/transcode:/transcode
            - ${DOWNLOAD_FOLDER}/television:/data/tvshows
            - ${DOWNLOAD_FOLDER}/movies:/data/movies
            - ${DOWNLOAD_FOLDER}/music:/data/music
        restart: unless-stopped
        # devices:
        #     - /dev/dri/card0:/dev/dri/card0 #your devices go here
        #     - /dev/dri/renderD128:/dev/dri/renderD128 #may be different
        image: plexinc/pms-docker:plexpass
    
    arch-qbittorrentvpn:
        container_name: qbittorrentvpn
        hostname: qbittorrentvpn
        cap_add: 
            - NET_ADMIN
        ports:
            - '6881:6881'
            - '6881:6881/udp'
            - '6969:6969'
            - '8118:8118'
        network_mode: host #6565
        restart: unless-stopped
        volumes:
            - '/home/${USER}/media-config/data:/data'
            - '/home/${USER}/media-config/config:/config'
            - '/etc/localtime:/etc/localtime:ro'
            - ${DOWNLOAD_FOLDER}:/downloads
        env_file:
          - qbittorrentvpn.env
        environment:
            - VPN_CLIENT=openvpn
            - STRICT_PORT_FORWARD=yes
            - ENABLE_PRIVOXY=yes
            - LAN_NETWORK=192.168.1.0/24 #possibly different
            - 'NAME_SERVERS=209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177,84.200.70.40,1.0.0.1'
            - VPN_INPUT_PORTS=1234
            - VPN_OUTPUT_PORTS=5678
            - DEBUG=false
            - WEBUI_PORT=6969 #not the default change in webui
            - UMASK=000
            - PUID=1000
            - PGID=1000
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=1
        image: binhex/arch-qbittorrentvpn

    jackett:
        image: ghcr.io/linuxserver/jackett
        container_name: jackett
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Sao_Paulo
            - AUTO_UPDATE=true 
            - RUN_OPTS=<run options here>
        volumes:
            - /home/${USER}/media-config/jackett/config:/config
            - /home/${USER}/media-config/data:/downloads
        network_mode: host #9117
        restart: unless-stopped
    
    radarr:
        image: ghcr.io/linuxserver/radarr
        container_name: radarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Sao_Paulo
        volumes:
            - /home/${USER}/media-config/radarr:/config
            - ${DOWNLOAD_FOLDER}:/downloads
        network_mode: host #7878
        restart: unless-stopped

    sonarr:
        image: ghcr.io/linuxserver/sonarr
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Sao_Paulo
        volumes:
            - /home/${USER}/media-config/sonarr:/config
            - ${DOWNLOAD_FOLDER}:/downloads
        network_mode: host #8989
        restart: unless-stopped
    bazarr:
        image: lscr.io/linuxserver/bazarr:latest
        container_name: bazarr
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/Sao_Paulo
        volumes:
            - /home/${USER}/media-config/bazarr:/config
            - ${DOWNLOAD_FOLDER}/movies:/downloads
            - ${DOWNLOAD_FOLDER}/data/television:/tv
        ports:
          - 6767:6767
        network_mode: host #6767
        restart: unless-stopped
    # lidarr:
    #     image: ghcr.io/linuxserver/lidarr
    #     container_name: lidarr
    #     environment:
    #         - PUID=1000
    #         - PGID=1000
    #         - TZ=America/Sao_Paulo
    #     volumes:
    #         - /home/${USER}/media-config/lidarr:/config
    #         - ${DOWNLOAD_FOLDER}:/music 
    #         - /home/${USER}/media-config/data:/downloads 
    #     network_mode: host #8686:8686
    #     restart: unless-stopped
  
    # prowlarr:
    #     image: lscr.io/linuxserver/prowlarr:develop
    #     container_name: prowlarr
    #     environment:
    #       - PUID=1000
    #       - PGID=1000
    #       - TZ=America/Sao_Paulo
    #     # put your directories here
    #     volumes:
    #       - /home/${USER}/media-config/prowlarr:/config
    #     network_mode: host #9696
    #     restart: unless-stopped
